defaults:
  database: &database
    host: localhost
    port: 5432
    adapter: postgresql
    database: booyah
    username: postgres
    password:

development:
  database:
    <<: *database
    host: localhost
    port: 5432
    adapter: postgresql
    database: booyah

production:
  database:
    <<: *database
    host: $DB_HOST
    port: 5432
    adapter: postgresql
    database: booyah_production
    username: $DB_USERNAME
    password: $DB_PASSWORD